### ISSUE TITLE
Cosas por mejorar

### ISSUE THREAD

**Issue by Esti92** [truji9/BuscaminasIS#1]
Poner en:
TableroBuilderN1/N3 los metodos que tiene N2.

**Comment by Esti92** [comment]
Poner correctamente el crono.

**Comment by Esti92** [comment]
Observer de las banderas no lo hace bien.
if(pObjeto.equals("false")){
                contBanderas--;
            }else{
                contBanderas++;
            }

**Comment by truji9** [comment]
El crono funciona de manera correcta ya.
Los TableroBuilderN1/N3 ya tienen todos los metodos.
Y lo de las banderas esta corregido.
